### ISSUE TITLE
Problem with sharedParams number in controller

### ISSUE THREAD

**Issue by tschnz** [collective-soundworks/soundworks#14]
When using `sharedParams.addNumber(...)`, then the controller shows a numberBox input field with 4 arrow buttons. 2 look like standard number in-/decrease buttons (right hand side of input pointing up/down). When using those, the number in the input field is shortly shown then immediately is deleted (always shows 1). If you input the number manually, it's also deleted. When using the other 2 (looks custom made) arrow buttons (pointing left/right on the sides of the numberBox) I get the error:

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
/js/controller.js:2020:24  TypeError: step is undefined
```

**Comment by b-ma** [comment]
Hi,

Yes, the component needs a `step` to work properly, for example:
```
sharedParams.addNumber('my-number', 'my-label', 0, 1, 0.001, 0.707);
```
where the parameters are : key, label, min, max, step, defaultValue

(be aware that this version of soundworks will be deprecated soon)

**Comment by MAOShea** [comment]
I'm always happy to see activity on this project :-)

M

**Comment by b-ma** [comment]
I hope it will be a good surprise for you in September then :)

**Comment by MAOShea** [comment]
Ooh!

**Comment by tschnz** [comment]
Works! Thanks for that very fast reply!! There are still two sets of buttons but that's alright :) And if I could add something to my wishlist for the next version: optional limits :)

**Comment by b-ma** [comment]
Perfect !
