### ISSUE TITLE
Server-side enter() function called three times on check-in from player.

### ISSUE THREAD

**Issue by MAOShea** [collective-soundworks/soundworks#2]
Hi,

I'm building a Soundworks (SW) application for use during an electronica band's live performance. While I've got a very basic prototype running, there are a couple of details that I'd need help with. I can't tell if I'm mis-using SW (and thus need to correct my code) or if it may require an enhancement to SW to make my application work properly.

In short: 
- my prototype has 1 conductor experience and 5 player experiences (1 player experience = 1 song performed by a live band)
- I have a mechanism that lets the conductor switch between player experiences, this *seems* to work OK but I suspect that this point needs attention too, later
- I *am* able to emit events from an experience's player-side and to have them trigger the handler in the matching server-side experience *but* ...
- on clicking past the Welcome to Drops (I'm building my thing starting from Drops) screen on a player, the enter() method of *all* of my server side Experiences is called *three times* (A, B, C, D, E, A, B, C, D, E, A, B, C, D, E).

Because I set up event handlers up in the enter(client) method of an experience, and because the enter(client) is called 3 times at startup, all my events fire 3 times. 

Can you please help find out why this is happening? I can provide some code if you're interested.

In the meantime, I am going to use [node-debug](https://www.npmjs.com/package/node-debug) to do some analysis into how the server side behaves. I'll tell you if I make progress from that angle.

Regards,

Michael O'Shea

**Comment by NorbertSchnell** [comment]
Hi Michael,

We are talking about Soundworks 1.x right ?

Did you associate the server-side experiences to the corresponding client type by calling “super(<cilent type>)" ?
Any chance that we could have a look at the code ?

Best,
Norbert

**Comment by MAOShea** [comment]
Norbert, good to talk again!
from an extract of package.json, we see that we're using Soundworks 1.0.1

  "dependencies": {
    "babel-runtime": "^6.6.1",
    "debug": "^2.1.2",
    "soundworks": "collective-soundworks/soundworks.git#v1.0.1",
    "source-map-support": "^0.4.0"
  },

About super(<client type>), all my server-side Experiences call     super('player');

If you want, I can provide code about how I set everything up on client side and server side?

Cheers.

Michael

**Comment by NorbertSchnell** [comment]
> On 11 May 2016, at 08:00, MAOShea <notifications@github.com> wrote:
> 
> About super(), all my server-side Experiences call super('player');
> 
They have to call super with the respective client type (e.g. 'conductor'). 

> If you want, I can provide code about how I set everything up on client side and server side
> 
Yes, that could certainly help helping...
N.

**Comment by MAOShea** [comment]
Ah, I am also doing super('conductor') in the conductor Experience both client and server side. So I don't think that that's the problem. It must be said that events are being sent and received OK between all the objects required. It's just that enter() is called 3 times instead of 1 time at the startup.

I suspect that it's due to how I'm initialising the program at load time. I will send my code this evening with some explanations regarding its structure and what it's doing.

Thanks for your help so far !

Michael

**Comment by MAOShea** [comment]
Hi Norbert,

I've sent you my code to your email because github doesn't let me attach a tgz archive produced by **npm pack** to this message (even if I rename it to zip).

You'll see that I re-used Drops as my starting point instead of Template. I forget what the reason was for this. Maybe because Drops actually had a concrete example of events passed from client to server and back.

If you try to build it, notice that I had to add my own build-css script that calls node-sass. In my environment, the css folder just wasn't being built! Not a problem, with that tweak it works fine now, I just need to do npm run build-css once at some point.
 
See in my code how the Experiences are implemented, each with a client-side and a server side equivalent. Scripts SwitcherExperience.js, PlayerExperience.js, Perf4Muters.js, PerfCacophony.js, PerfSquance.js, PerfStandby.js, PerfTapTest.js are player experiences.

The server-side conductor ConductorExperience.cs script doesn't have a client-side equivalent. I don't know if this is a problem. Its purpose is to declare a shared param **performance**. The conductor client/view seem to be OK with this, correctly displaying a UI for that parameter and correctly changing it on the server by clicking on the buttons in the UI.

The index.js of the server:
- creates an instance of each of the server sides of the player Experiences offered by the application
- creates an instance of the ConductorExperience class that declares a shared property called **performance** that will be changed by clicking buttons in the conductor

The server-side SwitcherExperience doesn't contain any functionality other than to send trace messages to the console. The client-side SwitcherExperience subscribes to changes to shared param **performance**. It then emits its own event **switchperf** 

The index.js of the conductor client only serves to programmatically define that shared parameter **performance** is controlled with a set of radio buttons in its UI. It does not have a client-side equivalent of the server-side ConductorExperience that I described higher up.

The index.js of the player client:
- creates an instance of each of the client side player experiences offered by the application (including the SwitchPerf Experience)
-  subscribes to the **switchperf** event to call function switchperformance()

How this works:
- the conductor clicks on the radio buttons in his/her view to switch from one Experience (a.k.a. performance) to another. 
- when a button is clicked, this changes the **performance** parameter on the server
- the SwitchPerf Experience in each client receives the signal of the change and emits its own **switchperf** event that is picked up by the main script in the index.js of the client
- the handler for that event in index.js called switchperformance()

Before looking at how I switch the views (which I already know is not right) please simply run the server and connect to it on localhost:8000. Click on the Welcome screen and you will see in the server's console (the Node.js command line) that all 5 of my experiences are entered **three** times. At this point we haven't even had a connection from the conductor nor have we tried to do any switching. Whatever is going wrong there is caused by problems in the startup.

Please see for yourself in the code I emailed you how I switch between the views. I'm very much aware that this is not the correct way to do this but it is the only way that I was able to switch between PerfStandby and PerfTapTest. Trying to add more of the remaining performance experiences breaks what little bit does work.

Notice that I have experimented with calling .hide() and .stop() on the experience that I'm switching *away* from and calling .start() and .show() on the experience that I'm switching *to*. I landed on .done() and .start() but I know that those have their own problems too. I'm hoping that you can tell me which is the better approach.

**Comment by MAOShea** [comment]
I'm putting a diagram together that illustrates the above. I hope to have it done this evening.

**Comment by MAOShea** [comment]
OK, attached, 
![soundworksplaid](https://cloud.githubusercontent.com/assets/4534104/15227919/bc1c8cc0-1889-11e6-8141-21d1ddd3a321.jpg)
the diagram of the above.

**Comment by MAOShea** [comment]
Here's a diagram.
![soundworksplaid](https://cloud.githubusercontent.com/assets/4534104/15228271/a5bdb196-188b-11e6-9591-d24916e866c4.jpg)

**Comment by MAOShea** [comment]
Here's a diagram : 
![soundworksplaid](https://cloud.githubusercontent.com/assets/4534104/15228347/00630f7e-188c-11e6-9fca-63474d3917be.jpg)

**Comment by MAOShea** [comment]
What I have found so far: 
- when a client connects, each of its Experiences does this.send('enter')
- I have three Experiences : the 'enter' signal is being sent 3 times to the server

I continue to research the issue.

**Comment by NorbertSchnell** [comment]
Hi Michael,

We didn’t have the time to look into your code yet.
Please have a look into the “Soundfield” example, which shows you how to do 2 clients.
Each client should have a single experience.

If you don’t manage to solve this before, we’ll look into this next week.

Best,
Norbert

**Comment by MAOShea** [comment]
Thanks for your reply.

I will look at Soundfield.

About "each client should have a single experience" ... are you likely to expand SoundWorks to include my requirement? If so, what would the timeframe be?

Have a nice weekend. :-)

**Comment by NorbertSchnell** [comment]
Which requirement ?
Having multiple experiences in a single client ?

**Comment by MAOShea** [comment]
yes, that ! :-)

Cheers,

Michael

**Comment by MAOShea** [comment]
From what I've seen of the code, it seems so close to being possible :-D

I was tempted to start making my own changes to SoundWorks to support that but I figured that I should check with you guys first.

Michael

**Comment by NorbertSchnell** [comment]
Why you would want a single client to have multiple experiences? They should run in parallel or one after the other?

There are multiple solutions to both, parallel or serial activities/processes. None of them should require changing soundworks. 

LOne solution would be to define multiple sub-experiences within a single experience. 
Both is possible (maybe not on the level of wa, in

**Comment by MAOShea** [comment]
Norbert, I don't want to change SoundWorks, I just want to achieve my goal. 

How do you suggest I do sub-experiences? 

I'm looking at SoundField now. Thanks.

I'm open to suggestions.

Just to clarify: I'd like to control the switching between sub-experiences from the conductor's view.

How would you go about doing that?

Michael

**Comment by NorbertSchnell** [comment]
> On 15 May 2016, at 11:39, Norbert Schnell <Norbert.Schnell@ircam.fr> wrote:
> 
> Why you would want a single client to have multiple experiences? They should run in parallel or one after the other?
> 
> There are multiple solutions to both, parallel or serial activities/processes. None of them should require changing soundworks. 
> 
> One solution would be to define multiple sub-experiences within a single experience. 

Oops, this wasn't complete...

This basically means that you would manage when to make appear one or another audiovisual rendering (call it sub-experience or whatever) at one it another moment within an experience. 

Another possibility is to redefine the "sub-experience" on a lower level of the API by extending the parent classes if Experience : Scene, Activity or Process. 

In any case, the fundamental question is : are these (sub)experiences running in parallel or one at the time ? 
In the parallel case the next question is how to share the view, in the serial case it is more about how to get from one to the other. 

So, parallel or serial ?

Why not just having 3 different objects (encapsulating your 3 modes of rendering) that you use inside the (one and only) experience. 

N.

**Comment by MAOShea** [comment]
Norbert, thanks for your reply.

The answer to the fundamental question then: the subexperiences (or a new concept : "interactions" ?) run in serial. Each song in the concert will have its own subexperience (interaction?)

When the band switch from one song to the next, a signal from the conductor will make the displays of the audience's player experience switch to show the subexperience for the next song.

I like your idea of extending Scene, Activity or Process. I'll give that a go.

When I'm done, I'll be happy to donate my results as a new sample SW project. 

Do you think we can close this issue with : only one experience per client connection, implement a "sub-experience" ? If necessary, I'll open a fresh issue to track my progress on the new solution direction.

Regards,

Michael

**Comment by NorbertSchnell** [comment]
Yes, let's close this. 

In fact, I would simply stay within the experience and switch from one interaction to another on an "enum" shared parameter set from the conductor. 

See the experience simply as something that waits (on the client side) for all services being ready before "entering". On the server side it collects the clients that "entered" in an array.
It maybe would make sense to extend the Scene only (and still not necessarily) if the users would advance  individually through different scenes or - even more - if different scenes would follow each other depending on complex sets of conditions that you could express using binary signals. 

Evidently, the is nothing bad about formalizing a song into a base class with an init/start/stop interface that makes sure that each song is implemented so that ones a song stopped there aren't any listeners or rendering processes that continue to use the CPU, right ?

Best,
Norbert

**Comment by MAOShea** [comment]
That's a great explanation ! Thanks.

Michael
