### ISSUE TITLE
Add option to suppress reload if tab is going inactive 

### ISSUE THREAD

**Issue by schlenger** [collective-soundworks/soundworks#36]
**Issue:** We want to display a stream on client/player side. While everything works fine while the tab is in the foreground, there is reload triggered on the page if I put the tab into the background. Therefore, the stream is aborted and could not be continued. 

The behavior was different in soundworks v2 and I wonder if there is an option to suppress the "reload on inactive tab" action. I guess this is part of the feature how the currently active clients are handled and therefore intended.

**Comment by b-ma** [comment]
Hi, yep there is an option, just replace the following in the `index.js` of the concerned client

```js
// initQoS(client);
initQoS(client, { visibilityChange: false });
```

**Comment by schlenger** [comment]
Just tested it - works like charm, thanks :)
