### ISSUE TITLE
Grouping several parameter updates into one message?

### ISSUE THREAD

**Issue by MAOShea** [collective-soundworks/soundworks#4]
Hi guys,

is it at all possible to group shared parameter updates so that several changes can be bundled into one message to the subscribers instead of each change to each parameter being sent as separate messages?

To illustrate: my server side code has a method that is executed once a second. Each time, it calculates a new value for 3 parameters, X, Y and N. 
The update calls are:
        this.params.update('X', newX);
        this.params.update('Y', newY);
        this.params.update('N', newN);
Each of these calls seem to cause a separate message to be sent to each of the clients.

It would be really cool if it were possible to somehow group the 3 updates into one message.

Is this possible? If not, are there plans to make it possible?

Regards,

Michael O'Shea

**Comment by b-ma** [comment]
Hey Michael,

For the moment it's not possible, but it's true that it would be a very nice feature !
Where are preparing a new release at this moment so we will see if we can integrate that feature in the Roadmap.

We keep you in touch and thanks for the suggestion !

Benjamin
