### ISSUE TITLE
Soundworks as a NPM module some time?

### ISSUE THREAD

**Issue by MAOShea** [collective-soundworks/soundworks#6]
Hi guys!

are you planning on making Soundworks into a NPM module at some point?

I am looking at programming SW stuff using MS Visual Studio's NodeJS Tools extension. This development environment is happier working with fully compliant modules. 

I realise that it's probably not very high on your priorities list.

I may end up doing it myself, if you want.

Cheers,

Michael

**Comment by b-ma** [comment]
Hi Michael, 

It took some time but its finally done: https://www.npmjs.com/package/soundworks

Cheers,
Benjamin

**Comment by MAOShea** [comment]
T'es un chef! Merci!

Maillequeule
