### ISSUE TITLE
ParameterBag getDefaults always returns undefined for all parameters

### ISSUE THREAD

**Issue by semiaddict** [collective-soundworks/soundworks#70]
ParameterBag's `getDefaults` method always returns undefined for all parameters.
This is thus also the case for BaseSharedState's `getDefaults` , and is likely caused by a typo in https://github.com/collective-soundworks/soundworks/blob/d6ee4f6bed2eb8d23a93613ad1a3c3ff54a0f5bd/src/common/ParameterBag.js#L419

Which should likely be:
```js
defaults[name] = def.default;
```
(ie. without the __s__ in the last __default__)

**Comment by b-ma** [comment]
Hey, thanks for the feedback, fixed in 3a2eae6
