### ISSUE TITLE
State Definition - introduce `required` option

### ISSUE THREAD

**Issue by b-ma** [collective-soundworks/soundworks#95]
A parameter that must be defined when creating the state, e.g.

```js
{
   uuid: {
     type: 'string',
     required: true,
   },
}
```

Throw error if not given in init values

**Comment by jipodine** [comment]
Good to have.

Should we also throw an error if the definition contains a `default` attribute?

**Comment by b-ma** [comment]
release in v4.0.0-alpha.29
